---
# tasks file for TwitterBot
- name: install pip
  package:
    name: python3-pip
    state: present
- name: install twitter API for python
  pip:
    name: python-twitter
    state: "{{ state }}"
    executable: "pip3"
- name: user for cronjob
  user:
    name: "{{ twitbot_user }}"
    comment: TwitterBot
    home: "{{ twitbot_home }}"
    system: yes
    state: "{{ state }}"
- name: directory should be absent
  file:
    path: "{{ twitbot_home }}"
    state: "{{ state }}"
  when: state != "present"
- name: ensure directory is private
  file:
    path: "{{ twitbot_home }}"
    state: directory
    owner: "{{ twitbot_user }}"
    mode: 0700
  when: state == "present"
- name: copy python script
  copy:
    src: "{{ role_path }}/files/twitbot.py"
    dest: "{{ twitbot_bin }}"
    owner: "{{ twitbot_user }}"
    mode: 0700
  when: state == "present"
- name: install configuration from template
  template:
    src: "{{ role_path }}/templates/twitbot.cf.j2"
    dest: "{{ twitbot_conf }}"
    owner: "{{ twitbot_user }}"
    mode: 0600
    validate: "{{ twitbot_bin }} --config %s --validate"
  when: state == "present"
- name: schedule reporting
  cron:
    name: TwitterBot
    job: "{{ twitbot_bin }} --config {{ twitbot_conf }}"
    special_time: daily
    user: "{{ twitbot_user }}"
    state: "{{ state }}"
