---
# tasks file for TwitterBot
- name: removes legacy versions
  file:
    path: "{{twitbot_home}}/twitter-bot.{{item}}"
    state: absent
  with_items: ["cf", "py"]
- name: install pip
  package:
    name: python-pip
    state: present
- name: install twitter API for python
  pip:
    name: python-twitter
    state: present
- name: user for cronjob
  user:
    name: "{{ twitbot_user }}"
    comment: TwitterBot
    home: "{{ twitbot_home }}"
    system: yes
- name: ensure directory is private
  file:
    path: "{{ twitbot_home }}"
    state: directory
    owner: "{{ twitbot_user }}"
    mode: 0700
- name: copy python script
  copy:
    src: "{{ role_path }}/files/twitbot.py"
    dest: "{{ twitbot_bin }}"
    owner: "{{ twitbot_user }}"
    mode: 0700
- name: install configuration from template
  template:
    src: "{{ role_path }}/templates/twitbot.cf.j2"
    dest: "{{ twitbot_conf }}"
    owner: "{{ twitbot_user }}"
    mode: 0600
    validate: "{{ twitbot_bin }} --config {{ twitbot_conf }} --validate"
- name: schedule reporting
  cron:
    name: TwitterBot
    job: "{{ twitbot_bin }} --config {{ twitbot_conf }}"
    special_time: daily
    user: "{{ twitbot_user }}"
